config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  root 'posts#index'
  namespace :admin do
    resources :users, only: %i[index edit update]
  end
  resources :users, only: %i[new create edit update show] do
    member do
      patch 'withdrawl'
      get 'posts'
    end
  end
  resources :password, only: %i[edit update]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :posts, only: %i[new create show destroy] do
    resources :replies, only: %i[create destroy]
  end
  resources :likes, only: %i[create destroy]
  resources :favorites, only: %i[index create destroy]
  get 'search', to: 'search#search'
  get 'terms', to: 'text#terms'
  get 'privacy', to: 'text#privacy'
end

app/views/shared/_admin_user_index.html.erb
<table class = "table table-striped table-light table-bordered align-middle table-sm admin-table">
  <tr class = "table-dark">
    <th>ID</th>
    <th>ユーザー名</th>
    <th>メールアドレス</th>
    <th>アクティブ<br>ユーザー</th>
    <th>備考<br>（管理者用）</th>
    <th>編集<br>（管理者用）</th>
    <th>強制退会</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td>
        <% if user.active %>
          <p>○</p>
        <% else %>
          <p>退会済</p>
        <% end %>
      </td>
      <td><%= user.note %></td>
      <td><%= link_to "編集", edit_admin_user_path(user.id), class: "btn btn-outline-primary btn-sm" %></td>
      <td><%= link_to "強制退会", withdrawl_user_path(user.id), class: "btn btn-outline-danger btn-sm", method: :patch, data: {confirm: "本当に退会させますか？"} if user.active %></td>
    </tr>
  <% end %>
</table>
<%= paginate @users, :remote => true %>

app/views/shared/_footer.html.erb
<footer>
  <div class = "footer-wrapper d-flex flex-column align-items-center">
    <div>
      <ul class = "footer-menu d-flex flex-column flex-lg-row align-items-center fw-bold">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "利用規約", terms_path %></li>
        <li><%= link_to "プライバシーポリシー", privacy_path %></li>
      </ul>
    </div>
    <p class = "copyright">Copyright © 2021 oda</p>
  </div>
</footer>

app/views/shared/_guest_login.html.erb
<%= form_with scope: :session, url: login_path, local: true do |form| %>
  <%= form.hidden_field :email, value: "guest@email.co.jp" %>
  <%= form.hidden_field :password, value: "guestpass" %>
  <div class = "btn-position guest-btn-position">
    <p>ユーザー登録せずに利用する方はこちらへ</p>
    <%= form.submit "ゲストユーザーでログインする", class: "btn btn-outline-secondary login-btn" %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class = "header-wrapper navbar d-flex justify-content-between">
    <div class = "header-flex-box1 fw-bold fst-italic navbar-brand">
      <%= link_to "公務員NEXT", root_path %>
    </div>
    <div class = "header-flex-box2">
      <%= form_with url: search_path, method: :get, class: "search-box", local: true do |form| %>
        <div class = "input-group search-box-text">
          <%= form.search_field :keyword, class: "form-control", placeholder: "キーワードで検索" %>
          <span class = "search-btn">
            <%= form.submit "\uf002", class: "search-icon" %>
          </span>
        </div>
      <% end %>
    </div>
    <div class = "header-flex-box3">
      <% if current_user && current_user.admin? %>
        <%= link_to " 管理者画面", admin_users_path, class: "fas fa-users-cog btn btn-dark" %>
      <% else %>
        <%= link_to " 相談する", new_post_path, class: "far fa-comment-dots btn btn-primary fw-bold" %>
      <% end%>
    </div>
    <% if current_user %>
      <div class="header-flex-box4">
        <button class = "navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span class = "navbar-toggler-icon"></span>
        </button>
        <div class ="login-header-menu collapse navbar-collapse" id="navbar-menu">
          <ul class = "navbar-nav fw-bold">
            <li class = "nav-item">
              <%= link_to "ユーザー情報", user_path(current_user.id), class: "nav-link" %>
            </li>
            <li class = "nav-item">
              <%= link_to "設定", edit_user_path(current_user.id), class: "nav-link" %>
            </li>
            <li class = "nav-item">
              <%= link_to "パスワードの変更", edit_password_path(current_user.id), class: "nav-link" %>
            </li>
            <li class = "nav-item">
              <%= link_to "これまでした相談", posts_user_path(current_user.id), class: "nav-link" %>
            </li>
            <li class = "nav-item">
              <%= link_to "お気に入り", favorites_path, class: "nav-link" %>
            </li>
            <li class = "nav-item">
              <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <div class="header-flex-box4 navbar-expand-lg">
        <button class = "navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span class = "navbar-toggler-icon"></span>
        </button>
        <div class ="not-login-header-menu collapse navbar-collapse" id="navbar-menu">
          <ul class = "navbar-nav">
            <li class = "nav-item">
              <%= link_to " ログイン", login_path, class: "fas fa-sign-in-alt nav-link" %>
            </li>
            <li class = "nav-item">
              <%= link_to " 新規登録", new_user_path, class: "fas fa-user-plus nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </nav>
</header>

app/views/shared/_post_list.html.erb
<div class = "post-list-wrapper" id="post-page">
  <% posts.each do |post| %>
    <div class = "post-list d-flex justify-content-center align-items-center p-3">
      <div class = "reply-count">
        <p>回答数</p>
        <p style = "font-size: 24px;"><%= "#{post.replies_count}件"%></p>
      </div>
      <div class = "post-right">
        <div class = "post-create">
          <div class = "post-user d-flex flex-column flex-lg-row mb-1">
            <div class ="me-3">
              <i class = "fas fa-user-edit"></i><span><%= " #{post.user.active_user_name}" %></span>
            </div>
            <div>
              <i class = "far fa-comment-dots"></i><span><%= " #{datetime_format(post.created_at)}" %></span>
            </div>
          </div>
          <div class = "post-title mb-1"><%= link_to "#{post.title}", post_path(post.id) %></div>
        </div>
        <div class = "post-edit">
          <i class = "fas fa-reply"></i><span><%= " #{datetime_format(post.most_recent_update)}" %></span>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate posts, :remote => true %>
</div>

app/views/shared/_reply_form.html.erb
<div class = "reply-box-infomation">
  <%= react_component("UserModal", props: { user: reply.user }, prerender: false) %>
  <p><%= "返信日時：#{datetime_format(reply.created_at)}" %></p>
</div>
<div class = "reply-box-content">
  <%= safe_join(reply.content.split("\n"),tag(:br)) %>
</div>
<div class = "d-flex flex-row justify-content-between">
  <%= react_component("Like", props: { replyId: reply.id, likeId: reply.like_by(current_user)&.id, likeCount: reply.likes.size, user: current_user }, prerender: false) %>
  <%= link_to "削除する", post_reply_path(post, reply.id), method: :delete, class: "btn btn-outline-danger btn-sm" if reply_delete_permission?(reply) %>
</div>

app/views/shared/_user_form.html.erb
<div class = "row form-group form-parts">
  <%= form.label :name, "ユーザー名", class: "col-sm-3 col-form-label annotation" %>
  <div class = "col-sm-9 d-flex align-items-center">
    <%= form.text_field :name, class: "form-control", placeholder: "ユーザー名（20文字以下）" %>
  </div>
</div>
<div class = "row form-group form-parts">
  <%= form.label :email, "メールアドレス", class: "col-sm-3 col-form-label annotation" %>
  <div class = "col-sm-9 d-flex align-items-center">
    <%= form.email_field :email, class: "form-control", placeholder:"メールアドレス" %>
  </div>
</div>
<% unless current_user%>
  <div class = "row form-group form-parts">
    <%= form.label :password, "パスワード", class: "col-sm-3 col-form-label annotation" %>
    <div class = "col-sm-9 d-flex align-items-center">
      <%= form.password_field :password, class: "form-control", placeholder: "パスワード（６文字以上）" %>
    </div>
  </div>
  <div class = "row form-group form-parts">
    <%= form.label :password_confirmation, "パスワード(確認)", class: "col-sm-3 col-form-label annotation" %>
    <div class = "col-sm-9 d-flex align-items-center">
      <%= form.password_field :password_confirmation, class: "form-control", placeholder: "上記と同じパスワードを入力" %>
    </div>
  </div>
<% end %>
<div class = "row form-group form-parts">
  <%= form.label :age, "年代", class: "col-sm-3 col-form-label annotation" %>
  <div class = "col-sm-9 d-flex align-items-center flex-wrap">
    <div class = "pe-3"><%= form.radio_button :age, "10代", class: "form-check-input" %>10代</div>
    <div class = "pe-3"><%= form.radio_button :age, "20代", class: "form-check-input" %>20代</div>
    <div class = "pe-3"><%= form.radio_button :age, "30代", class: "form-check-input" %>30代</div>
    <div class = "pe-3"><%= form.radio_button :age, "40代", class: "form-check-input" %>40代</div>
    <div class = "pe-3"><%= form.radio_button :age, "50代", class: "form-check-input" %>50代</div>
    <div class = "pe-3"><%= form.radio_button :age, "60代以上", class: "form-check-input" %>60代以上</div>
  </div>
</div>
<div class = "row form-group form-parts">
  <%= form.label :organization, "組織", class: "col-sm-3 col-form-label annotation" %>
  <div class = "col-sm-9 d-flex align-items-center">
    <div class = "pe-3"><%= form.radio_button :organization, "国家公務員", class: "form-check-input" %>国家公務員</div>
    <div class = "pe-3"><%= form.radio_button :organization, "地方公務員", class: "form-check-input" %>地方公務員</div>
  </div>
</div>
<div class = "row form-group form-parts">
  <%= form.label :job, "職種", class: "col-sm-3 col-form-label annotation" %>
    <div class = "col-sm-9 d-flex align-items-center">
      <div class = "pe-3"><%= form.radio_button :job, "事務系", class: "form-check-input" %>事務系</div>
      <div class = "pe-3"><%= form.radio_button :job, "技術系", class: "form-check-input" %>技術系</div>
  </div>
</div>
<div class = "row form-group form-parts">
  <%= form.label :status, "現在の状況", class: "col-sm-3 col-form-label annotation" %>
    <div class = "col-sm-9 d-flex align-items-center">
      <div class = "pe-3"><%= form.radio_button :status, "現職", class: "form-check-input" %>現職</div>
      <div class = "pe-3"><%= form.radio_button :status, "退職済", class: "form-check-input" %>退職済</div>
  </div>
</div>
<div class = "row form-group form-parts">
  <%= form.label :introduction, "自己紹介", class: "col-sm-3 col-form-label" %>
  <div class = "col-sm-9 d-flex align-items-center">
    <%= form.text_area :introduction, class: "form-control", placeholder: "自己紹介（１００文字以内）" %>
  </div>
</div>

app/views/shared/_user_infomation.html.erb
<div class = "card-box">
  <p class = "card-name">ユーザー名</p>
  <p class = "card-text"><%= user.name %></p>
</div>
<div class = "card-box">
  <p class = "card-name">メールアドレス</p>
  <p><%= user.email %></p>
</div>
<div class = "card-box">
  <p class = "card-name">年代</p>
  <p><%= user.age %></p>
</div>
<div class = "card-box">
  <p class = "card-name">組織</p>
  <p><%= user.organization %></p>
</div>
<div class = "card-box">
  <p class = "card-name">職種</p>
  <p><%= user.job %></p>
</div>
<div class = "card-box">
  <p class = "card-name">現在の状況</p>
  <p><%= user.status %></p>
</div>
<div class = "card-box">
  <p class = "card-name">自己紹介</p>
  <p><%= user.introduction %></p>
</div>